type User @table {
  displayName: String!
  email: String
  photoUrl: String
  createdAt: Timestamp!
}

type RCCar @table {
  user: User
  name: String!
  model: String
  description: String
  createdAt: Timestamp!
}

type Track @table {
  name: String!
  location: String
  description: String
  createdAt: Timestamp!
}

type GameResult @table {
  user: User
  game: String
  score: Int!
  date: Date!
  notes: String
  createdAt: Timestamp!
}